use_frameworks!

platform :ios, '8.0'

target 'TCustomizedTransition_Example' do
  pod 'TCustomizedTransition', :path => '../'

  target 'TCustomizedTransition_Tests' do
    inherit! :search_paths

    
  end
end
